### ISSUE TITLE
{action}_ready methods should wait until all bindings have done initial resolve

### ISSUE THREAD

**Issue by dennym** [voltrb/volt#272] opened 2015-08-16 20:28 UTC
I have this in the view and it gets correctly served from the corresponding controller. That controller has a {action}_ready method with

      `$('.clickable-row').click(function() {
        console.log('clicked');
      });`

That is the view with the table rows. The first row is for testing purpose manually written and all the other rows a created via the `.each` block from the component view. The final rendered view has a table with couple of table rows but the first one is still static for testing purpose. The little jquery snippet above only triggers on the static row and not the dynamic rows from the `.each` block. 

    <tbody>
      <tr class="clickable-row" >
        <td>Testrow</td>
      </tr>
      {{ _objects.each do |object| }}
        <:blub:tablerow model="{{ object }}" />
      {{ end }}
    </tbody>

And the component tablerow.

    <:Body>
      <tr class="clickable-row" >
        <td>{{ object._data }}</td>
      </tr>

The jquery snippet should work on all table rows, shouldn't it? 
Any ideas or suggestions?

Edit: While digging though other issue I stumbled over https://github.com/voltrb/volt/issues/184#issuecomment-98793210 
So it seems for now its the wanted behavior. After creating `def tablerow_ready` with the jquery snippet on the blub controller it worked like intended.

**Comment by ryanstout** [comment] 2015-08-16 22:28
@dennym sorry, I'm having trouble understanding what your saying.  When does it get fired?

**Comment by dennym** [comment] 2015-08-17 11:30
updated

**Comment by ryanstout** [comment] 2015-08-20 17:16
Ok, I think I see the problem.  So the _objects.each may not be run until after the _ready method gets called.  I want to make it where the _ready method doesn't get called until after all of the sub-bindings render.  (But I haven't added that yet, sorry)  Right now there's two things you can do:
1) move the contents into a subview and use its _ready method. (as you did), or 
2) move _objects to the model.  If the model is set to a promise, it will wait until the promise resolves before it renders.

I'm going to change the name and leave this open as a todo.

**Comment by ryanstout** [comment] 2015-08-20 18:07
Actually, closing this, since its a duplicate of #184

**Closed by ryanstout** 2015-08-20 18:07 UTC
Labels: enhancement
