### ISSUE TITLE
Parser does not warn on unclosed tags.

### ISSUE THREAD

**Issue by rubydesign** [voltrb/volt#250] opened 2015-07-16 14:56 UTC
I had a tags ">" missing on the closing tag. Research got me to the closing tag feature and tests.
The feature works unexpected in this case. Anyway here is a test (sandlebars_parser_spec.rb) that produces very unexpected results:

``` ruby
  it 'should close tags at the right place with more tags present' do
    html = '<div>text</div  <p>ptext</p>'
    match = '<div>text</div> <p>ptext</p>'
    test_html(html,match)
  end
```

This produces, the following, swallowing the p tag.

``` html
<div>text</div>ptext
```

No idea how to fix this, but i would expect more error logs when the <div  is encountered would help the user. Possibly logging is better than auto-closing as that produces unexpected results (always closes after the last) but the user doesn't even know anything was wrong

**Comment by dennym** [comment] 2015-07-26 21:05
Could you give more information on the actual problem and what you did with what?

**Comment by dancinglightning** [comment] 2015-07-27 07:31
Hi,
i thought bringing it down to a test case would be good. Don't you agree that the test case above is a fail?
Just add that to the sandlebars_parser_spec and try.

I had mistyped and a closing div tag was missing the closing > . the results were rather unexpected, and checking what went on resulted in the test case above, which imho should produce the match, not what it does.

**Comment by ryanstout** [comment] 2015-08-16 23:08
@dancinglightning ideally yea, that would give you some "unclosed tag" error or something.  If I get time, I would like to rewrite the parser (what I have now is mostly copied from another project and modified for bindings).  The problem is its a big endeavor (html is the hardest thing to parse ever, hehe), and the original parser I borrowed from didn't support alerting on close tags.  (Because it does what html does and just tries to make it work)  If anyone is ambitious and wants to give it a shot (or look into integrating something like https://github.com/nevir/ruby-gumbo)  Originally I was using nokogiri, then walking the dom looking for bindings, but that was really slow, so it would be nice to be able to do a sax style parser, so we don't even have to construct objects as we parse.

That said, I'll leave this open for now, and once I get some time I'll try to rework the current one.

**Closed** 2021-07-18 20:31 UTC
